### ISSUE TITLE
session ID not set

### ISSUE THREAD

**Issue by Da5hes** [PowerShellEmpire/Empire#126]
i've encountered a strange thing today, our main test agent stopped responding and there are no logs for his calls, and for any new agents that we try to add we get in the debug console:
    /news.asp requested from None at x.x.x.x
    /news.asp requested by x.x.x.x with no session ID

*restarting the listeners or setting new listeners and stagers did not help, empire just stopped working as intended 
*reseting the database helped for a one time run, as soon as we tried to exit the agent and initiate it again, the problem appeared again

**Comment by HarmJ0y** [comment]
Can you do a Wireshark dump of the traffic on the control server to see if any of the traffic is getting through? Normal agent comms with the default config should look something like this:

<img width="714" alt="normal_comms" src="https://cloud.githubusercontent.com/assets/5504523/12277014/2372d2e6-b947-11e5-8b58-87c3cc6a4476.png">

Is the SESSIONID present in the dump?

**Comment by Da5hes** [comment]
no session ID is present
and the response is Not Found

GET /news.asp HTTP/1.1
User-Agent: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36
Host: xxxx
Connection: Keep-Alive

HTTP/1.0 404 Not Found
Server: Microsoft-IIS/8 
Date: Wed, 13 Jan 2016 10:26:45 GMT

**Comment by HarmJ0y** [comment]
So the SessionID is set as a script variable here https://github.com/PowerShellEmpire/Empire/blob/master/data/agent/agent.ps1#L114

And here is where the header is built for requests- https://github.com/PowerShellEmpire/Empire/blob/master/data/agent/agent.ps1#L900-L906

So if the SessionID isn't being preserved (haven't this before), you can try adding in debug output (to the console or a debug file) in the Get-Task function in order to check the state of the various script variables when a tasking is retrieved. I can't recreate this issue on my machine and don't have an idea of what the root cause might be, so I'm not sure what a fix would be without additional information.

**Comment by Da5hes** [comment]
i ended up reseting the db again, my guess is that it was caused by uri changes
