### ISSUE TITLE
Double Port While Setting Listener Host

### ISSUE THREAD

**Issue by clthomps** [PowerShellEmpire/Empire#174]
## Empire Version
Empire 1.5

## OS Information (Linux flavor, Python version)
Kali / Python 2.7.9

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

When setting listener Host an additional port is appended to the end of the IP. This only seem to happen when using a : to separate the port from the IP

## Screenshot of error, embedded text output, or Pastebin link to the error
<img width="1080" alt="screen shot 2016-04-05 at 10 31 23 am" src="https://cloud.githubusercontent.com/assets/5048945/14285584/17e1000a-fb1a-11e5-89f5-86c5132556a5.png">

**Comment by clthomps** [comment]
It seems to be fixed after removing Empire and reinstalling.

**Comment by 0rigen** [comment]
I believe that this is still an issue.  I ran into this on a fresh installation of Empire and I think I've tracked down why it may have seemed to disappear.  It depends on whether or not you specify the protocol.  Below is the issue I was going to submit before seeing this one.

## Empire Version
1.5.0

## OS Information (Linux flavor, Python version)
Parrot OS, Linux 4.1.7 i686
Python 2.7.9

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

Expectation: Setting the Host parameter of a Listener along with port should display in the Listener 'info' as: _IP:Port_

Instead, when the protocol is not specified, the 'info' display appends the port number onto the end of the 'Host' value, which already contains the port, displaying it as _IP:Port:Port_

Steps:
1) Set up new listener
2) _set Host 8.8.8.8:9999_
3) _info_
4) Observe that the Host parameter is displayed as _http://8.8.8.8:9999:9999_
5) _set Host http://8.8.8.8:9999_
6) _info_
7) Observe that the Host parameter is properly displayed as _http://8.8.8.8:9999_

My attempt at chasing down the logic at issue:
listeners.py:170 assigns ['Host']['Value'] to the entire string that was passed in, then it checks to see if a port was specified.  If it was, listeners.py:175 appends the port onto the string (which already contains the port specification)

## Screenshot of error, embedded text output, or Pastebin link to the error
![image](https://cloud.githubusercontent.com/assets/8540616/15330996/2dd9a75c-1c2d-11e6-99ca-543beeb16699.png)


## Any additional information
This does not affect the actual operation of the listener; just makes the display funny.
