### ISSUE TITLE
Switching from Usemodule to Interacting with agent

### ISSUE THREAD

**Issue by honeyfairy** [PowerShellEmpire/Empire#190]
## Empire Version
Latest

## OS Information (Linux flavor, Python version)
Kali

This is a support question.

If I am in a `usemodule` context, how do I go back to interacting with the agent? Is the only way to type `agents`, then `interact NAME`?

For example:

`(Empire: collection/keylogger) execute

agents

interact XXXXX`

By doing the above, will it stop the keylogger running?

**Comment by forkmind** [comment]
If in the keylogger module options, you have specified the name of one of your agents (you do, because it would have throw an error if it wasn't the case as it's a required option), then it will run as a background job for this agent. If you interact with this agent later, no matter the path you choose to interact with it, the job would still run and can be viewed by typing `jobs`. From [the Powershell Empire website] (http://www.powershellempire.com/?page_id=283) : 
>When a module runs continuously in the background (like keyloggers or clipboard theft), a started job ID will be returned. If you type jobs in an agent menu, the currently active background jobs will be returned. To kill a job, use jobs kill JOB_ID.

**Comment by HarmJ0y** [comment]
After running the keylogger, type **back** and you should return to the agent menu (FYI **help** displays all current commands in any menu).

And @forkmind is correct, the keylogger is jobbified. **jobs kill <ID>** will kill the specified job ID.
