### ISSUE TITLE
mass-commands appear to not function

### ISSUE THREAD

**Issue by Viss** [PowerShellEmpire/Empire#249]
## Empire Version
Empire: PowerShell post-exploitation agent | [Version]: 1.5.0

## OS Information (Linux flavor, Python version)
Ubuntu 16.04, python 2.7

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
setting 'Agents all' on a usermodule like logon_passwords, for example returns no output to the user when run - the output only is displayed when one interacts with an agent. It does appear to populate the creds db though, which is handy, but its impossible to tell in any meaningful way if the run worked or if any run errored without manually touching every single agent. It appears to do this after you have several dozen agents. I'm not sure how to troubleshoot this on my side, but I'm on a gig with several hundred shells and mass-anything doesn't seem to work at all.

**Comment by enigma0x3** [comment]
Currently, you won't see output from any agent outside of the agent's context. This is because it gets rather annoying when you have a long running job (Such as UserHunter) running on 1 agent and the output floods the console when interacting with other agents. To combat this, we constructed it in a way that output for each agent is only displayed when you are interacting with it.

If the module completes on an agent, you should creds in the credential store for each host. Running logon passwords on a ton of agents at once tends to lock things up (as expressed here as well: https://github.com/PowerShellEmpire/Empire/issues/113). I recommend doing them in chunks if you have a large set of computers to run the module on.
