### ISSUE TITLE
Jobs don't auto-complete

### ISSUE THREAD

**Issue by leesoh** [PowerShellEmpire/Empire#256]
## Empire Version
1.5.0

## OS Information (Linux flavor, Python version)
Linux HOSTNAME 4.5.0-kali1-amd64 #1 SMP Debian 4.5.5-1kali1 (2016-06-06) x86_64 GNU/Linux

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
Could be a feature request, but when killing jobs using the jobs kill <job name>, tab completion doesn't work.

**Comment by enigma0x3** [comment]
Hey @leesoh,
The reason jobs don't tab complete right now is because the running jobs are "registered" on the target and not the server. Due to this, the only way to get an updated job list is to task the agent to run "TASK_GETJOBS" (which is executed anytime you type "jobs") and then post the results back to the server. Since the jobs start/end on the agent on the target system, keeping an updated backend DB list of jobs is a challenge. We will start to look how we can implement this in a way that makes sense, but with how things are setup now, they won't be tab completable.

Thanks!
