### ISSUE TITLE
Keylogger Module

### ISSUE THREAD

**Issue by ih8ra1nydayz** [PowerShellEmpire/Empire#49]
thanks for the great tool !
I tested the keylogger module today and get a lot of incorrect characters.
Windows was running in Virtualbox and the keyboard was German.
Empire was running in Kali but virtual with Parallels Desktop for mac.
Maybe thats the problem ?
My input was twitter.com and im getting itter.com 
or input was google.com and i was getting googgle.com.

**Comment by HarmJ0y** [comment]
So the keylogger is pulled from PowerSploit. This issue https://github.com/mattifestation/PowerSploit/issues/50 has a great explanation from the authors- " I would prefer SetWindowsHookEx but that requires that a dll be loaded into the targeted processes...I have been trying to come up with a better option, but the bottom-line is any change will have trade-offs. I am going to add the polling interval as an argument so that it can be easily changed between 30, 35, 40 and 45. Basically, everyone holds down keys differently when typing and all key-loggers that use this technique suffer from this drawback."

So this is a restriction for the approach, but at this point there's not a great solution.

**Comment by ih8ra1nydayz** [comment]
Thanks for the declaration !
