### ISSUE TITLE
issue with code_execution/invoke_reflectivepeinjection module

### ISSUE THREAD

**Issue by amainyebriggs** [PowerShellEmpire/Empire#58]
show [!] Error: module produced an empty script
![screenshot from 2015-10-08 23 49 47](https://cloud.githubusercontent.com/assets/13424678/10382018/955647d8-6e17-11e5-8001-26b0729ea5da.png)
 

because needed required variables are set to false 
  how do i set it to true

**Comment by enigma0x3** [comment]
Hi @amainyebriggs,
This is now fixed. You can view it in this commit: https://github.com/PowerShellEmpire/Empire/commit/a46bdac77dac6d2aebfec4eb3ab56b99f9326309

Thanks

**Comment by amainyebriggs** [comment]
i was thinking it could be nice to make veil generate powershell payload

because in some cases cmd is blocked and the launcher.bat will not execute on test system 
and the only way is to deliver it using metasploit  reflective dll post exploitation module
to inject into a process  whichs gives empire a session, but thats blah , i really will love a great flexibility on empire, where it will be able to generate a payload using veil-evasion and java, and also being able to deliver cobaltstrike beacon over foreign listener

cause the cobalt strike post exploitation command"powershell" delivers empire payload so it will be nice to be nice to the nice guy

cobaltbeacon<=============>empire

**Comment by enigma0x3** [comment]
@amainyebriggs,
Since Empire is a post-exploitation agent, you have many different ways to execute a beacon (or any other payload) from within Empire (since you have code execution on the box). Currently, beacon dll's don't inject well using Invoke-dllinjection. 

You can do the same thing with Empire to deliver a beacon payload as you would do with Cobalt Strike and an Empire payload. From CS, you can export a .ps1 package and then throw a function around the whole script. You can then do a "scriptimport /path/to/beacon.ps1". Once it imports, you can do a "scriptcmd <functionName>" and it will execute the beacon payload.

**Comment by amainyebriggs** [comment]
thanks bro

**Comment by enigma0x3** [comment]
No problem. You can also read about how Empire integrates with frameworks like CS and Metasploit here: http://www.powershellempire.com/?page_id=133
