### ISSUE TITLE
Modified "DefaultProfile" doesn't stage correctly

### ISSUE THREAD

**Issue by mubix** [PowerShellEmpire/Empire#61]
```
  DefaultProfile    True        /a.asp,/b.asp,/c.asp|Moz        Default communication profile for the agent.
                                illa/5.0 (compatible; MSIE 10.0;
                                Windows NT 7.0; InfoPath.3; .NET
                                CLR 3.1.40767; Trident/6.0; en-
                                US)
```
Setting results in failed staging (launcher stager still tries to pull index.asp, then index.php and index.jsp)

**Comment by mubix** [comment]
Found the setup in the setup_database.py. Is there a way in the interface to change the stagers?

**Comment by enigma0x3** [comment]
The defaultProfile contains the URIs that are used after staging for normal comms. Empire will always use index.asp, index.jsp and index.php for the staging process by default. As you mentioned, these values are set in setup_database.py. You can edit setup_database.py to change the stage0, stage1 and stage2 URI values if you need to. Since these are stored in empire.db, there is no way currently to change these staging URIs from the interface.

As for your failed staging issue, I have index.asp, index.jsp and index.php as my staging URIs and then set the DefaultProfile to:
/a.asp,/b.asp,/c.asp|Mozilla/5.0 (compatible; MSIE 10.0;Windows NT 7.0; InfoPath.3; .NETCLR 3.1.40767; Trident/6.0; en-US)

Which is what you have set. When viewing the traffic, empire reaches out to index.asp, index.php and index.jsp to stage and then uses a.asp, b.asp and c.asp for comms.

Are you saying that setting the DefaultProfile resulted in failed staging for you?

**Comment by mubix** [comment]
@enigma0x3 Turned out to be a totally borked VM that was causing the failure at Stage2 for some reason, finally tried it out on another VM and worked perfectly. I'll close this and make a feature request to see an interface in the actual "gui" for changing the stager URLs

**Comment by mubix** [comment]
Thanks for testing it out @enigma0x3 sorry for the trouble

**Comment by enigma0x3** [comment]
No worries @mubix, glad you got it working!
