### ISSUE TITLE
empire notification 

### ISSUE THREAD

**Issue by amainyebriggs** [PowerShellEmpire/Empire#76]
empire does not give a notification in case an agent dies or stops calling home

just like msfconsole , pupy remote admin tool, cobaltstrike 
will be good to know when an agents dies
so i dont send commands to dead agents and when we dont get response we start thinking i have been block or network

**Comment by enigma0x3** [comment]
@amainyebriggs,
If you do a "list" on your agents, it will give you the time that they last check in. You can also type "list stale" and it will list your dead agents. I suggest that you check your stale agents if you think an agent may be dead.

**Comment by amainyebriggs** [comment]
okay will try that
since no  auto notification

**Comment by amainyebriggs** [comment]
am having issues running exe in memory from powershell

**Comment by amainyebriggs** [comment]
like pupy its very easy

**Comment by enigma0x3** [comment]
ok. Details would be nice. It's hard to help if all you provide is "am having issues". What issues? Are you getting an error? How are you generating it?

**Comment by amainyebriggs** [comment]
okay thanks i will do that

**Comment by HarmJ0y** [comment]
frameworks that use an asynchronous agent can't really let you know for sure if an agent 'dies', since it's not an interruption in stream based communication. For example, while Cobalt Strike lets you know if the communication between SMB links are severed, it does not alert you if an agent 'dies' (we use CS). There are plenty of situations where systems may be hibernated, switch networks, stand up/down a VPN.  "list stale" and "remove stale" allow you to list and manipulate agents outside of their checkin window.

**Comment by amainyebriggs** [comment]
okay
