### ISSUE TITLE
Auto run on new session

### ISSUE THREAD

**Issue by mubix** [PowerShellEmpire/Empire#80]
It'd be nice to have a way to automatically run a script or two when a new session comes in. Is there any way to do this already?

**Comment by mlinton** [comment]
I'll second this request.

**Comment by HarmJ0y** [comment]
No way to do this now but we've talked about it. Will start looking into it again.

**Comment by HarmJ0y** [comment]
This is going to take a bit of rearchitecting, but we intend to do it I promise.

**Comment by HarmJ0y** [comment]
There is now a branch that *should* implement this functionality: https://github.com/PowerShellEmpire/Empire/tree/script_autorun

You can set any module to autorun with "set Agent autorun" : 
<img width="462" alt="set_autorun" src="https://cloud.githubusercontent.com/assets/5504523/11326715/b1c44d08-913e-11e5-9b82-063ed1d5cb01.png">

<img width="390" alt="autorun_message" src="https://cloud.githubusercontent.com/assets/5504523/11326716/b63bfbd8-913e-11e5-9a77-12285fdaa61b.png">

To clear the current autorun, on the agents menu do "(Empire: agents) > clear autorun".

One note of warning- this required a small database schema update, so in order to work correctly you will need to run ./setup/reset.sh or ./setup/set_database.py . This will mean that you will lose the connection information for any current agents and listeners, so only update the schema at the start of a new engagement.

After I can someone else to test, and anyone can confirm this appears to work, we will merge to master.

**Comment by HarmJ0y** [comment]
Merged to master.

**Comment by coom** [comment]
Nice feature, but as soon as you combine it with some auto privilege escalation,it result in an infinite loop.
