### ISSUE TITLE
Feature Request to enhance ability to inject agent into other processes

### ISSUE THREAD

**Issue by MarkBaggett** [PowerShellEmpire/Empire#82]
When a credential is discovered by keylooging, searching Netlogon or other method I would like an easy way to put that into the credential store manually.   OR
allow user to optionally specify credentials to be used for lateral/invoke_psexec, manage/psinject as well as manage/inject_wmi.  This would also allow you to specify credential and spread to targets where only port 445 is accessible.  

Also, please allow ComputerName to be an optional field for manage\psinject.  I popped a non-administrator, keylogged the local admin, then wanted to specify the admin creds and manage/psinject into the same host to privilege escalate the agent.   However, if you use Invoke-WmiMethod (as I am sure this method does) and specify the -ComputerName argument you will get a "User credentials cannot be use for local connections" error.  (and remotely executing it to escalate isn't always an option because of UAC AccountTokenFilterPolicy)

Have I told you lately that you guys are awesome?   Thanks!

**Comment by HarmJ0y** [comment]
Right now you can do "[creds add DOMAIN username Password](http://www.powershellempire.com/?page_id=114)" to manually add credentials to the database. For a more fine-grained approach, you can always run "sqlitebrowser ./data/empire.db" and manually edit the **credentials** table.

I'm confused as to how you're envisioning **ComputerName** to fid into manage/psinject exactly. Since PSInject is a reflective DLL that's injected into a different/existing process space, I don't know how we would do an "inject as" with different credentials.

One thing we could possibly so is combining the runas and spawn modules to produce a management/spawnas module to spawn a new stager with specified plaintext credentials. Thoughts?

**Comment by MarkBaggett** [comment]
"cred add" is what I was looking for.  I didn't see that when I looked in the code.  Sorry.

My ComputerName suggestion wont work.   Ignore that request and pretend I was smart enough not to suggest that.     

If I have an agent running on a target as a non-admin.   I wanted to privilege escalate by using  lateral/inject_wmi on the same target and specify the local administrator username and password.   I can not come in remotely as the local administrator because of UAC and AccountTokenFilterPolicy, but locally I should be able to specify the admin account to escalate.    I think I can do this now using "cred add" and invoke_psexec.   

Is there a better (intended) way for me to escalate from a non-privileged user to a privileged user given key logged credentials?   

Thanks again.

**Comment by MarkBaggett** [comment]
Hmm.. Nope actually manage/psinject, manage/spawn and lateral/psexec wont allow me to use CredID :(
I think I am looking for manage/runas, that invokes the stager as another user instead of a command like notepad.   I suppose I could create a dll, upload it to the drive and use runas to launch the dll, but that is messy.

**Comment by HarmJ0y** [comment]
Yep, which is why I was thinking a "spawnas" type of function, or adapting the spawn function to accept plaintext credentials. Will have to test but I think it would be possible (no need to WMI/etc. from the box to itself). You would need to bypassuac afterwards however, but not likely not too bad.

**Comment by HarmJ0y** [comment]
There's a first pass as a "management/spawnas" module in the master branch now https://github.com/PowerShellEmpire/Empire/commit/7db7ec6bbc42d95d33237fd4d9e542737833668d

<img width="1106" alt="spawnas" src="https://cloud.githubusercontent.com/assets/5504523/11023568/b15c940a-864a-11e5-8acf-f563b8c09624.png">

This unfortunately drops a temporary file to disk due to some length restriction stuff, but it *should* work (though needs more testing).

**Comment by leechristensen** [comment]
Could the LogonUser/CreateProcess* API's help here?

CreateProcess*
https://msdn.microsoft.com/en-us/library/windows/desktop/ms682431(v=vs.85).aspx
https://msdn.microsoft.com/en-us/library/windows/desktop/ms682429(v=vs.85).aspx

LogonUser
https://msdn.microsoft.com/en-gb/library/windows/desktop/aa378184(v=vs.85).aspx

**Comment by HarmJ0y** [comment]
Damn you lee, you and your logic!

That's definitely a better way to go, will try to adjust soon.

**Comment by leechristensen** [comment]
Haha currently off gallivanting in Europe.  Might have some time on the flight home this next weekend if you guys can wait that long :)

If you do go this route, may want to consider creating a per-host token manager.  I only mention this because ideally we'd only have to call LogonUser once and then use the token to create processes.  That way, if there's a need to create multiple using those creds, then we'll only have to generate one logon event (otherwise we'd create one every time we spawn a process with the creds).

**Comment by HarmJ0y** [comment]
So you're envisioning the exposed LogonUser API logic being contained within the agent itself? Then keep a list of custom objects that preserve the pointer to the created tokens? Seems interesting but might take a bit of rearchitecting under the hood if we do go that route.

**Comment by leechristensen** [comment]
Yeah, that's the idea.  Tokens gathered via LogonUser and other means (e.g. stealing other process tokens, named pipe impersonation, etc.) would be stored in the token manager.  Main goal with it is just to prevent repeating actions if they aren't necessary (logon events, exploits, etc.).  Considerably more work though.  Probably much easier to just start with using the CreateProcess* API's for now :)
